name: Deploy Canary Build
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    branches: main
    paths:
      - src/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  PROJECT_FILE: RecipeMechanic.sln
  RELEASE_TITLE: Canary Build
  RELEASE_TAG: canary
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: |
          dotnet publish ${{ env.PROJECT_FILE }} --output build
          $artifacts = (Get-ChildItem -Path build -Recurse).FullName
          New-Item -Path artifacts -ItemType Directory
          Compress-Archive -Path $artifacts -DestinationPath artifacts/${{ github.event.repository.name }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: artifacts/*
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          files: artifacts/*
          title: ${{ env.RELEASE_TITLE }}
          automatic_release_tag: ${{ env.RELEASE_TAG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}